(function () {
  'use strict';
  var tree = null, selectedId = 'root', selectedPieceOwnerId = null, counter = 1, expanded = {root:true}, undoStack=[], redoStack=[];
  function snapshot(){return JSON.stringify({tree:tree,selectedId:selectedId,counter:counter});}
  function remember(){if(tree){undoStack.push(snapshot());if(undoStack.length>40)undoStack.shift();redoStack=[];}}
  function restoreState(raw){try{var state=JSON.parse(raw);tree=state.tree;selectedId=state.selectedId||'root';counter=state.counter||counter;render();}catch(_e){}}
  function undo(){if(!undoStack.length)return;redoStack.push(snapshot());restoreState(undoStack.pop());}
  function redo(){if(!redoStack.length)return;undoStack.push(snapshot());restoreState(redoStack.pop());}
  window.Modular3DHierarchyUndo=undo;window.Modular3DHierarchyRedo=redo;
  document.addEventListener('click',function(event){var target=event.target&&event.target.closest&&event.target.closest('button');if(!target)return;var mutation=['hierarchy_split','hierarchy_unsplit','hierarchy_duplicate','hierarchy_reset'];if(mutation.indexOf(target.id)<0)return;var node=tree&&nodeById(selectedId),message='';if(target.id==='hierarchy_reset')message='¿Restablecer toda la configuración jerárquica?';if(target.id==='hierarchy_unsplit'&&node&&(node.children||[]).length)message='Eliminar esta división también eliminará sus espacios y contenidos hijos. ¿Continuar?';if(target.id==='hierarchy_split'&&node&&(node.children||[]).length)message='Este espacio ya está dividido. Reemplazar la división eliminará su configuración hija. ¿Continuar?';if(message&&!confirm(message)){event.preventDefault();event.stopImmediatePropagation();return;}remember();},true);
  function id(x){ return document.getElementById(x); }
  function num(x, fallback){ var n=Number(id(x)&&id(x).value); return isFinite(n)?n:fallback; }
  function fresh(){ return {id:'root',name:'Módulo',content:'VACIO',front:'NINGUNO',frontCount:'AUTO',frontFit:'AUTO',frontJoint:1.5,overlayLeft:13.5,overlayRight:13.5,overlayTop:13.5,overlayBottom:13.5,drawers:0,shelves:0,gap:3,gapCenter:3,drawerGap:1.5,drawerHeight:0,drawerFrontStyle:'POR_CAJON',enclosure:{left:false,right:false,bottom:false,top:false,back:false},children:[]}; }
  function walk(node, fn, parent){ if(!node)return null;if(fn(node,parent))return node;for(var i=0;i<(node.children||[]).length;i++){var r=walk(node.children[i],fn,node);if(r)return r;}return null; }
  function nodeById(nodeId){ return walk(tree,function(n){return n.id===nodeId;}); }
  function parentOf(nodeId){ var result=null;walk(tree,function(n,p){if(n.id===nodeId){result=p;return true;}return false;});return result; }
  function isExternalFront(value){var front=String(value||'NINGUNO');return front!=='NINGUNO'&&front.indexOf('INTERNA')<0;}
  function clearExternalDescendants(node){(node.children||[]).forEach(function(child){if(isExternalFront(child.front))child.front='NINGUNO';clearExternalDescendants(child);});}
  function resolveFrontConflicts(node,ancestorHasExternal){var own=isExternalFront(node.front);if(ancestorHasExternal&&own){node.front='NINGUNO';own=false;}(node.children||[]).forEach(function(child){resolveFrontConflicts(child,ancestorHasExternal||own);});}
  function parse(expr,total,separator){
    var tokens=String(expr||'').split(':').map(function(v){return v.trim();}).filter(Boolean);if(tokens.length<2)throw new Error('Escribe al menos dos estaciones, por ejemplo 1:1.');
    var usable=total-separator*(tokens.length-1);if(usable<=0)throw new Error('Los tableros ocupan todo el espacio.');var fixed=0,weight=0;
    var parts=tokens.map(function(t){var m=t.match(/^(\d+(?:\.\d+)?)\s*(mm|cm|m)$/i);if(m){var q=+m[1]*(m[2].toLowerCase()==='m'?1000:(m[2].toLowerCase()==='cm'?10:1));fixed+=q;return{fixed:q};}m=t.match(/^(\d+(?:\.\d+)?)%$/);if(m){var p=usable*(+m[1])/100;fixed+=p;return{fixed:p};}if(/^auto$/i.test(t)){weight+=1;return{weight:1};}if(/^\d+(?:\.\d+)?$/.test(t)&&+t>0){weight+=+t;return{weight:+t};}throw new Error('No se reconoce «'+t+'».');});
    var remaining=usable-fixed;if(remaining<-0.01)throw new Error('Las medidas fijas exceden el espacio seleccionado.');if(remaining>0.01&&!weight)throw new Error('Añade AUTO o una proporción para repartir el sobrante.');
    return parts.map(function(p){return p.fixed!=null?p.fixed:remaining*p.weight/weight;});
  }
  function rearReserve(){var depth=num('prof_total',580),mode=id('lleva_respaldo')?id('lleva_respaldo').value:'SI';if(mode==='NO')return 0;var back=num('grosor_resp',6),distance=num('distancia_plano_posterior',0);if(back>=15)return Math.min(depth-1,distance+back);var count=id('cantidad_ajustes')?id('cantidad_ajustes').value:'AUTO',active=count==='AUTO'||Number(count)>0;return Math.min(depth-1,distance+(active?num('grosor_ajuste',num('espesor',15))+num('separacion_ajuste_respaldo',2):0)+back);}
  function bounds(){var depth=num('prof_total',580);return{x:num('grosor_izq',15),z:num('grosor_inferior',15),y:0,w:Math.max(1,num('ancho_total',600)-num('grosor_izq',15)-num('grosor_der',15)),h:Math.max(1,num('alto_total',760)-num('grosor_superior',15)-num('grosor_inferior',15)),d:Math.max(1,depth-rearReserve())};}
  function solve(node,box,list,separators){node.box={x:box.x,y:box.y,z:box.z,w:box.w,d:box.d,h:box.h};list.push(node);if(!node.split||(node.children||[]).length<2)return;var axis=node.split.axis,sep=node.split.physical?node.split.thickness:0,total=axis==='X'?box.w:(axis==='Z'?box.h:box.d),sizes=parse(node.split.expr,total,sep),cursor=axis==='X'?box.x:(axis==='Z'?box.z:box.y);node.children.forEach(function(child,i){var b={x:box.x,y:box.y,z:box.z,w:box.w,d:box.d,h:box.h};if(axis==='X'){b.x=cursor;b.w=sizes[i];}else if(axis==='Z'){b.z=cursor;b.h=sizes[i];}else{b.y=cursor;b.d=sizes[i];}solve(child,b,list,separators);if(i<sizes.length-1&&sep>0){separators.push({axis:axis,x:axis==='X'?cursor+sizes[i]:box.x,y:axis==='Y'?cursor+sizes[i]:box.y,z:axis==='Z'?cursor+sizes[i]:box.z,w:axis==='X'?sep:box.w,d:axis==='Y'?sep:box.d,h:axis==='Z'?sep:box.h,parent:node.id});}cursor+=sizes[i]+sep;});}
  function facadeBox(node,rootBox,seps){var b=node.box,j=Math.max(0,Number(node.frontJoint==null?1.5:node.frontJoint)),eps=.05;if(String(node.frontFit||'AUTO')==='CUSTOM')return{x:b.x-Math.max(0,Number(node.overlayLeft)||0),z:b.z-Math.max(0,Number(node.overlayBottom)||0),w:b.w+Math.max(0,Number(node.overlayLeft)||0)+Math.max(0,Number(node.overlayRight)||0),h:b.h+Math.max(0,Number(node.overlayTop)||0)+Math.max(0,Number(node.overlayBottom)||0),y:b.y};if(id('montaje_puerta')&&id('montaje_puerta').value==='EMBUTIDA')return{x:b.x+j,z:b.z+j,w:Math.max(1,b.w-j*2),h:Math.max(1,b.h-j*2),y:b.y};var left=Math.abs(b.x-rootBox.x)<eps?0:b.x,right=Math.abs((b.x+b.w)-(rootBox.x+rootBox.w))<eps?num('ancho_total',600):b.x+b.w,bottom=Math.abs(b.z-rootBox.z)<eps?0:b.z,top=Math.abs((b.z+b.h)-(rootBox.z+rootBox.h))<eps?num('alto_total',760):b.z+b.h;seps.forEach(function(s){if(s.axis==='X'){if(Math.abs((s.x+s.w)-b.x)<eps)left=s.x+s.w/2;if(Math.abs(s.x-(b.x+b.w))<eps)right=s.x+s.w/2;}if(s.axis==='Z'){if(Math.abs((s.z+s.h)-b.z)<eps)bottom=s.z+s.h/2;if(Math.abs(s.z-(b.z+b.h))<eps)top=s.z+s.h/2;}});return{x:left+j,z:bottom+j,w:Math.max(1,right-left-j*2),h:Math.max(1,top-bottom-j*2),y:b.y};}
  function geometry(){var nodes=[],seps=[],rootBox=bounds();solve(tree,rootBox,nodes,seps);nodes.forEach(function(n){n.display_name=label(n);var esFrenteCajon=n.content==='CAJONES_FRENTES';if((n.front&&n.front!=='NINGUNO'&&String(n.front).indexOf('INTERNA')<0)||esFrenteCajon)n.front_box=facadeBox(n,rootBox,seps);});return{root:tree,nodes:nodes,separators:seps};}
  function nodePath(n){var parts=[],cur=n;while(cur&&cur.id!=='root'){var p=parentOf(cur.id);parts.unshift(String((p.children||[]).indexOf(cur)+1));cur=p;}return parts;}
  function alpha(index){var result='',value=Math.max(0,index);do{result=String.fromCharCode(65+(value%26))+result;value=Math.floor(value/26)-1;}while(value>=0);return result;}
  function label(n){if(n.id==='root')return 'Módulo';var p=nodePath(n),zone=alpha((parseInt(p[0],10)||1)-1),suffix=p.slice(1).join('.');if(p.length===1)return 'Zona '+zone;if(p.length===2)return 'Espacio '+zone+'.'+suffix;return 'Subespacio '+zone+'.'+suffix;}
  function mountPlan(plan,g,rootBox){if(!plan)return;plan.innerHTML='';g.nodes.forEach(function(n){if((n.children||[]).length)return;var b=n.box,el=document.createElement('div');el.className='hierarchy-node'+(n.id===selectedId?' selected':'');el.dataset.node=n.id;el.style.left=((b.x-rootBox.x)/rootBox.w*100)+'%';el.style.width=(b.w/rootBox.w*100)+'%';el.style.top=((rootBox.z+rootBox.h-b.z-b.h)/rootBox.h*100)+'%';el.style.height=(b.h/rootBox.h*100)+'%';var content=n.front&&n.front!=='NINGUNO'?n.front:(n.content||'VACIO');el.innerHTML='<span class="hierarchy-node-label">'+label(n)+'<br>'+Math.round(b.w)+' × '+Math.round(b.h)+' mm<br>'+content.replace(/_/g,' ').toLowerCase()+'</span>';el.onclick=function(ev){ev.stopPropagation();select(n.id);};plan.appendChild(el);});g.separators.filter(function(s){return s.axis!=='Y';}).forEach(function(s){var el=document.createElement('i');el.className='hierarchy-separator';el.style.left=((s.x-rootBox.x)/rootBox.w*100)+'%';el.style.width=(s.w/rootBox.w*100)+'%';el.style.top=((rootBox.z+rootBox.h-s.z-s.h)/rootBox.h*100)+'%';el.style.height=(s.h/rootBox.h*100)+'%';plan.appendChild(el);});g.nodes.filter(function(n){return n.front&&n.front!=='NINGUNO';}).forEach(function(n){var internal=String(n.front).indexOf('INTERNA')>=0,b=internal?n.box:(n.front_box||n.box),el=document.createElement('div');el.className='hierarchy-parent-front'+(n.id===selectedId?' selected':'');el.dataset.node=n.id;el.style.left=((b.x-rootBox.x)/rootBox.w*100)+'%';el.style.width=(b.w/rootBox.w*100)+'%';el.style.top=((rootBox.z+rootBox.h-b.z-b.h)/rootBox.h*100)+'%';el.style.height=(b.h/rootBox.h*100)+'%';el.title=label(n)+' · '+n.front.replace(/_/g,' ');el.onclick=function(ev){ev.stopPropagation();select(n.id);};plan.appendChild(el);});}
  function renderTree(host,node,depth){if(!host)return;var has=(node.children||[]).length>0,row=document.createElement('div');row.className='hierarchy-tree-row';row.style.setProperty('--depth',depth);row.innerHTML='<button type="button" class="hierarchy-tree-toggle" '+(has?'':'disabled')+'>'+(has?(expanded[node.id]?'−':'+'):'·')+'</button><button type="button" class="hierarchy-tree-select '+(node.id===selectedId?'active':'')+'">'+label(node)+'</button><span class="hierarchy-tree-size">'+Math.round(node.box.w)+'×'+Math.round(node.box.h)+'</span>';row.children[0].onclick=function(){expanded[node.id]=!expanded[node.id];render(true);};row.children[1].onclick=function(){select(node.id);};host.appendChild(row);if(has&&expanded[node.id])node.children.forEach(function(child){renderTree(host,child,depth+1);});}
  function moveInspector(){var page=document.querySelector('.page.active'),inspector=document.querySelector('.hierarchy-inspector'),target=page&&page.id==='diseno'?id('review_inspector_slot'):document.querySelector('#interior .hierarchy-layout');if(inspector&&target&&inspector.parentNode!==target)target.appendChild(inspector);}
  function showEditorPage(pageId){document.querySelectorAll('.page').forEach(function(page){page.classList.toggle('active',page.id===pageId);});document.querySelectorAll('[data-page]').forEach(function(tab){tab.classList.toggle('active',tab.dataset.page===pageId);});moveInspector();}
  function render(selectionOnly){var g,status=id('hierarchy_status'),reviewStatus=id('review_status');try{g=geometry();[status,reviewStatus].forEach(function(s){if(s){s.className='hierarchy-status';s.textContent=g.nodes.length+' espacios · '+g.separators.length+' separadores físicos · cálculo exacto en mm';}});}catch(e){[status,reviewStatus].forEach(function(s){if(s){s.className='hierarchy-status error';s.textContent=e.message;}});return;}
    var rootBox={x:0,z:0,w:num('ancho_total',600),h:num('alto_total',760)};mountPlan(id('hierarchy_plan'),g,rootBox);mountPlan(id('review_plan'),g,rootBox);['hierarchy_tree','review_tree'].forEach(function(treeId){var host=id(treeId);if(host){host.innerHTML='';renderTree(host,tree,0);}});
    var path=[],cur=nodeById(selectedId);while(cur){path.unshift(cur);expanded[cur.id]=true;cur=parentOf(cur.id);}['hierarchy_breadcrumb','review_breadcrumb'].forEach(function(bid){var host=id(bid);if(!host)return;host.innerHTML=path.map(function(n){return '<button type="button" data-path="'+n.id+'">'+label(n)+'</button>';}).join(' › ');host.querySelectorAll('button').forEach(function(b){b.onclick=function(){select(b.dataset.path);};});});moveInspector();loadInspector();if(selectionOnly&&window.Modular3DView&&window.Modular3DView.selectSpace)window.Modular3DView.selectSpace(selectedPieceOwnerId?null:selectedId,false);else sync(); }
  function select(nodeId){if(!nodeById(nodeId))return;selectedPieceOwnerId=null;selectedId=nodeId;var cur=nodeById(nodeId);while(cur){expanded[cur.id]=true;cur=parentOf(cur.id);}render(true);}
  function loadInspector(){var n=nodeById(selectedId),b=n.box||bounds();id('hierarchy_summary').innerHTML='<b>'+label(n)+'</b><br>'+Math.round(b.w)+' × '+Math.round(b.h)+' × '+Math.round(b.d)+' mm';['left','right','bottom','top','back'].forEach(function(k){id('h_'+k).checked=!!(n.enclosure&&n.enclosure[k]);});if(id('h_top_mode'))id('h_top_mode').value=(n.enclosure&&n.enclosure.topMode)||'FULL';if(id('h_top_travesano'))id('h_top_travesano').value=(n.enclosure&&n.enclosure.topTravesano)||70;id('h_content').value=n.content||'VACIO';id('h_shelves').value=n.shelves||1;id('h_drawers').value=n.drawers||3;id('h_front').value=String(n.front||'NINGUNO').replace(/_VIDRIO/g,'').replace(/VIDRIO/g,'UNICA');id('h_front_count').value=String(n.frontCount||'AUTO');id('h_front_fit').value=n.frontFit||'AUTO';id('h_front_joint').value=n.frontJoint==null?1.5:n.frontJoint;id('h_overlay_left').value=n.overlayLeft==null?13.5:n.overlayLeft;id('h_overlay_right').value=n.overlayRight==null?13.5:n.overlayRight;id('h_overlay_top').value=n.overlayTop==null?13.5:n.overlayTop;id('h_overlay_bottom').value=n.overlayBottom==null?13.5:n.overlayBottom;id('h_hinge').value=n.hinge||'Izquierda';id('h_gap').value=n.gap==null?3:n.gap;id('h_gap_center').value=n.gapCenter==null?(n.gap==null?3:n.gap):n.gapCenter;if(id('h_drawer_gap'))id('h_drawer_gap').value=n.drawerGap==null?1.5:n.drawerGap;if(id('h_drawer_height'))id('h_drawer_height').value=n.drawerHeight==null?0:n.drawerHeight;if(id('h_drawer_front_style'))id('h_drawer_front_style').value=n.drawerFrontStyle||'POR_CAJON';toggleFields();}
  function toggleFields(){var c=id('h_content').value,front=String(id('h_front').value||''),external=front!=='NINGUNO'&&front.indexOf('INTERNA')<0,esFrentes=c==='CAJONES_FRENTES',hayTop=!!(id('h_top')&&id('h_top').checked),esTravesanos=hayTop&&id('h_top_mode')&&id('h_top_mode').value==='TRAVESANOS';document.querySelectorAll('.h-top-mode').forEach(function(x){x.style.display=hayTop?'grid':'none';});if(id('h_top_travesano_row'))id('h_top_travesano_row').style.display=esTravesanos?'grid':'none';document.querySelectorAll('.h-shelves').forEach(function(x){x.style.display=c==='REPISAS'?'grid':'none';});document.querySelectorAll('.h-drawers').forEach(function(x){x.style.display=c.indexOf('CAJONES')===0?'grid':'none';});document.querySelectorAll('.h-drawer-frentes').forEach(function(x){x.style.display=esFrentes?'grid':'none';});document.querySelectorAll('.h-front-puerta').forEach(function(x){x.style.display=esFrentes?'none':'grid';});document.querySelectorAll('.h-external-fit').forEach(function(x){x.style.display=external?'grid':'none';});document.querySelectorAll('.h-front-overlays').forEach(function(x){x.style.display=external&&id('h_front_fit').value==='CUSTOM'?'block':'none';});}
  function split(){var n=nodeById(selectedId);if(!n)return;var axis=id('hierarchy_axis').value,physical=id('hierarchy_physical').value==='FISICA',expr=id('hierarchy_expr').value,box=n.box||bounds(),total=axis==='X'?box.w:(axis==='Z'?box.h:box.d),sizes;try{sizes=parse(expr,total,physical?num('espesor',15):0);}catch(e){[id('hierarchy_status'),id('review_status')].forEach(function(s){if(s){s.className='hierarchy-status error';s.textContent=e.message;}});return;}n.split={axis:axis,expr:expr,physical:physical,thickness:num('espesor',15)};n.children=sizes.map(function(){return{id:'space_'+counter++,content:'VACIO',front:'NINGUNO',frontCount:'AUTO',frontFit:'AUTO',frontJoint:1.5,overlayLeft:13.5,overlayRight:13.5,overlayTop:13.5,overlayBottom:13.5,drawers:0,shelves:0,gap:3,gapCenter:3,drawerGap:1.5,drawerHeight:0,drawerFrontStyle:'POR_CAJON',enclosure:{},children:[]};});expanded[n.id]=true;selectedId=n.children[0].id;render();}
  function apply(){var n=nodeById(selectedId);if(!n)return;n.enclosure=n.enclosure||{};['left','right','bottom','top','back'].forEach(function(k){n.enclosure[k]=id('h_'+k).checked;});n.enclosure.topMode=id('h_top_mode')?id('h_top_mode').value:'FULL';n.enclosure.topTravesano=Math.max(20,num('h_top_travesano',70));n.content=id('h_content').value;n.shelves=Math.min(20,Math.max(0,parseInt(id('h_shelves').value,10)||0));n.drawers=Math.min(12,Math.max(0,parseInt(id('h_drawers').value,10)||0));n.front=id('h_front').value;n.frontCount=id('h_front_count').value||'AUTO';n.frontFit=id('h_front_fit').value||'AUTO';n.frontJoint=Math.max(0,num('h_front_joint',1.5));n.overlayLeft=Math.max(0,num('h_overlay_left',13.5));n.overlayRight=Math.max(0,num('h_overlay_right',13.5));n.overlayTop=Math.max(0,num('h_overlay_top',13.5));n.overlayBottom=Math.max(0,num('h_overlay_bottom',13.5));if(n.content==='CAJONES_PUERTA'&&n.front==='NINGUNO')n.front='PUERTA_UNICA';n.drawerFrontStyle=id('h_drawer_front_style')?id('h_drawer_front_style').value:'POR_CAJON';if(n.content==='CAJONES_FRENTES')n.front='NINGUNO';if(isExternalFront(n.front)){clearExternalDescendants(n);var ancestor=parentOf(n.id);while(ancestor){if(isExternalFront(ancestor.front))ancestor.front='NINGUNO';ancestor=parentOf(ancestor.id);}}n.hinge=id('h_hinge').value;n.gap=Math.max(0,num('h_gap',3));n.gapCenter=Math.max(0,num('h_gap_center',n.gap));n.drawerGap=Math.max(0,num('h_drawer_gap',1.5));n.drawerHeight=Math.max(0,num('h_drawer_height',0));render();}
  function sync(){var json=JSON.stringify(tree);window.__hierarchyJSON=json;try{var d=window.datosFormulario?window.datosFormulario():null;if(d&&window.Modular3DView)window.Modular3DView.update(d);}catch(_e){}}
  function bind(){tree=fresh();id('hierarchy_split').onclick=split;id('hierarchy_unsplit').onclick=function(){var n=nodeById(selectedId);n.split=null;n.children=[];render();};id('hierarchy_parent').onclick=function(){var p=parentOf(selectedId);if(p)select(p.id);};id('hierarchy_duplicate').onclick=function(){var n=nodeById(selectedId),p=parentOf(selectedId);if(!p)return;p.children.forEach(function(s){if(s.id!==n.id){['content','front','frontCount','frontFit','frontJoint','overlayLeft','overlayRight','overlayTop','overlayBottom','drawers','shelves','gap','gapCenter','drawerGap','drawerHeight','drawerFrontStyle','hinge'].forEach(function(k){s[k]=n[k];});s.enclosure=JSON.parse(JSON.stringify(n.enclosure||{}));}});render();};id('hierarchy_reset').onclick=function(){tree=fresh();selectedId='root';expanded={root:true};render();};id('h_content').onchange=toggleFields;['h_left','h_right','h_bottom','h_top','h_back'].forEach(function(key){id(key).addEventListener('change',function(){remember();apply();});});['h_content','h_front','h_front_count','h_front_fit','h_front_joint','h_overlay_left','h_overlay_right','h_overlay_top','h_overlay_bottom','h_hinge','h_shelves','h_drawers','h_gap','h_gap_center','h_drawer_gap','h_drawer_height','h_drawer_front_style','h_top_mode','h_top_travesano'].forEach(function(key){var field=id(key);if(field)field.addEventListener(field.tagName==='SELECT'?'change':'input',function(){remember();apply();});});
    ['external_front_scope','montaje_puerta','global_front_count_mode','global_front_count','global_front_auto_width','global_front_gap_left','global_front_gap_right','global_front_gap_top','global_front_gap_bottom','global_front_gap_center','global_front_hinge'].forEach(function(key){var field=id(key);if(field)field.addEventListener(field.tagName==='SELECT'?'change':'input',function(){var controls=id('global_front_controls');if(controls)controls.style.display=id('external_front_scope').value==='GLOBAL'?'block':'none';sync();});});
    ['ancho_total','alto_total','prof_total','grosor_izq','grosor_der','grosor_superior','grosor_inferior','espesor','grosor_resp','grosor_ajuste','separacion_ajuste_respaldo','distancia_plano_posterior','cantidad_ajustes','lleva_respaldo'].forEach(function(k){var e=id(k);if(e)e.addEventListener('input',render);});
    var original=window.datosFormulario;window.datosFormulario=function(){var d=original();d.geometry_contract_version='4';d.hierarchy_json=JSON.stringify(tree);d.hierarchy_geometry_json=JSON.stringify(geometry());d.selected_space_id=selectedId;return d;};
    window.addEventListener('modular3d:spaceSelected3D',function(event){var detail=event.detail||{};if(detail.id)select(detail.id);});
    window.addEventListener('modular3d:pieceSelected',function(event){var detail=event.detail||{},role=String(detail.role||''),shell=role.indexOf('shell-')===0,page=(shell||detail.category==='back'||detail.category==='adjustment')?'paneles':'interior',active=document.querySelector('.page.active');if(!active||active.id!=='diseno')showEditorPage(page);if(detail.ownerSpaceId&&nodeById(detail.ownerSpaceId)){selectedPieceOwnerId=detail.ownerSpaceId;selectedId=detail.ownerSpaceId;render(true);document.querySelectorAll('.hierarchy-node[data-node="'+detail.ownerSpaceId+'"]').forEach(function(node){node.classList.add('piece-owner');});}document.querySelectorAll('.hierarchy-plan').forEach(function(plan){if(shell)plan.classList.add('piece-'+role);});if(role.indexOf('separator-')===0){var separatorIndex=parseInt(String(detail.pieceId||'').replace('separator_',''),10),separators=document.querySelectorAll('.hierarchy-separator');if(isFinite(separatorIndex)&&separators[separatorIndex])separators[separatorIndex].classList.add('piece-selected');}setTimeout(function(){var field=detail.sourceField&&id(detail.sourceField),row=field&&field.closest&&field.closest('.row');if(row){row.classList.add('editor-focus');setTimeout(function(){row.classList.remove('editor-focus');},1600);}},40);});
    window.addEventListener('modular3d:editPieceSource',function(event){var detail=event.detail||{},shell=String(detail.role||'').indexOf('shell-')===0,page=(shell||detail.category==='back'||detail.category==='adjustment')?'paneles':'interior';showEditorPage(page);if(detail.ownerSpaceId&&nodeById(detail.ownerSpaceId)){selectedId=detail.ownerSpaceId;render(true);}setTimeout(function(){var field=detail.sourceField&&id(detail.sourceField);if(field){field.focus();field.scrollIntoView({behavior:'smooth',block:'center'});var row=field.closest&&field.closest('.row');if(row){row.classList.add('editor-focus');setTimeout(function(){row.classList.remove('editor-focus');},1800);}}},40);});
    document.querySelectorAll('[data-page]').forEach(function(tab){tab.addEventListener('click',function(){setTimeout(function(){moveInspector();render(true);},0);});});['step_prev','step_next'].forEach(function(buttonId){var button=id(buttonId);if(button)button.addEventListener('click',function(){setTimeout(function(){moveInspector();render(true);},0);});});
    var oldLoad=window.Modular3DLoadInitial;window.Modular3DLoadInitial=function(data){oldLoad(data);try{if(data.hierarchy_json){tree=typeof data.hierarchy_json==='string'?JSON.parse(data.hierarchy_json):data.hierarchy_json;selectedId=data.selected_space_id&&nodeById(data.selected_space_id)?data.selected_space_id:'root';expanded={root:true};resolveFrontConflicts(tree,false);walk(tree,function(n){var match=String(n.id||'').match(/(\d+)$/);if(match)counter=Math.max(counter,+match[1]+1);return false;});}}catch(_e){tree=fresh();}var controls=id('global_front_controls');if(controls)controls.style.display=id('external_front_scope').value==='GLOBAL'?'block':'none';render();};var controls=id('global_front_controls');if(controls)controls.style.display=id('external_front_scope').value==='GLOBAL'?'block':'none';render();if(window.__modular3dInitial)window.Modular3DLoadInitial(window.__modular3dInitial);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(bind,0);});else setTimeout(bind,0);
}());
