(function(){
  'use strict';
  var groups=['casco','interior','frentes','cajones','respaldo','ajuste','herrajes'];
  var overrides={},dimensionOverrides={},miterOverrides={},textures={},textureMeta={},selectedKey=null,selectedDetail=null,bound=false,pendingTexture='',pendingPieceTexture='';
  var LIBRARY_KEY='modular3d_material_library_v1';
  // Biblioteca de texturas incluidas con el plugin (imagenes genericas /
  // procedurales, no fotografias reales) -- mismo listado que
  // Modular_3D/textures/manifest.json, que es lo que Ruby usa para
  // resolver el "INCLUDED:<id>" a un archivo real al construir.
  var INCLUDED_TEXTURES=[
    {id:'blanco_liso',name:'Blanco liso',file:'blanco_liso.png',defaultScale:600},
    {id:'blanco_nube',name:'Blanco nube',file:'blanco_nube.png',defaultScale:600},
    {id:'negro_mate',name:'Negro mate',file:'negro_mate.png',defaultScale:600},
    {id:'gris_antracita',name:'Gris antracita',file:'gris_antracita.png',defaultScale:600},
    {id:'roble_claro',name:'Roble claro',file:'roble_claro.png',defaultScale:300},
    {id:'nogal_oscuro',name:'Nogal oscuro',file:'nogal_oscuro.png',defaultScale:300},
    {id:'wengue',name:'Wengué',file:'wengue.png',defaultScale:300}
  ];
  function includedTexture(id){return INCLUDED_TEXTURES.filter(function(t){return t.id===id;})[0]||null;}
  function textureDisplayUrl(source){var raw=String(source||'');if(raw.indexOf('INCLUDED:')!==0)return raw;var tex=includedTexture(raw.slice('INCLUDED:'.length));return tex?('../textures/'+tex.file):'';}
  function fillIncludedSelect(node){if(!node||node.options.length>1)return;INCLUDED_TEXTURES.forEach(function(tex){var option=document.createElement('option');option.value=tex.id;option.textContent=tex.name;node.appendChild(option);});}
  function id(name){return document.getElementById(name);}
  function value(name,fallback){var node=id(name);return node?node.value:fallback;}
  function checked(name){var node=id(name);return !!(node&&node.checked);}
  function pieces(){return window.Modular3DView&&window.Modular3DView.getPieces?window.Modular3DView.getPieces():[];}
  function groupFor(piece){return piece&&piece.group||'interior';}
  function groupColor(group){return value('material_'+group+'_color','#d5a66e');}
  function library(){try{return JSON.parse(localStorage.getItem(LIBRARY_KEY)||'[]')||[];}catch(_e){return [];}}
  function saveLibrary(items){localStorage.setItem(LIBRARY_KEY,JSON.stringify(items));renderLibrary();}
  function renderLibrary(){var node=id('material_library_select');if(!node)return;var previous=node.value;node.innerHTML='<option value="">Seleccionar...</option>';library().forEach(function(item,index){var option=document.createElement('option');option.value=String(index);option.textContent=item.name;node.appendChild(option);});node.value=previous;}
  function previewTexture(source){var node=id('material_texture_preview');if(!node)return;var shown=textureDisplayUrl(source);node.textContent=source?'Vista del material':'Sin textura';node.style.backgroundImage=shown?'url("'+shown.replace(/"/g,'%22')+'")':'';}
  function previewAt(nodeId,source,emptyText){var node=id(nodeId);if(!node)return;var shown=textureDisplayUrl(source);node.textContent=source?'Vista de la textura':emptyText;node.style.backgroundImage=shown?'url("'+shown.replace(/"/g,'%22')+'")':'';}
  function imageFileToData(file,done,fail){if(!file)return;var reader=new FileReader();reader.onerror=function(){if(fail)fail('No se pudo leer la imagen.');};reader.onload=function(){var image=new Image();image.onerror=function(){if(fail)fail('Formato no compatible. Usa JPG, PNG, WebP, BMP o GIF.');};image.onload=function(){var scale=Math.min(1,1024/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);done(canvas.toDataURL('image/jpeg',.9));};image.src=reader.result;};reader.readAsDataURL(file);}
  function resolved(piece){var key=piece.materialKey||piece.pieceId,custom=overrides[key],group=custom&&custom.group||groupFor(piece);if(custom&&custom.color)return custom.color;if(checked('material_unico')&&!checked('material_'+group+'_custom'))return value('material_global_color','#ffffff');return groupColor(group);}
  function selectDetail(detail){
    if(!detail)return;selectedDetail=detail;selectedKey=detail.materialKey||detail.pieceId;
    var current=overrides[selectedKey]||{},group=current.group||detail.materialGroup||'interior';
    id('material_piece_info').innerHTML='<b>'+String(detail.name||'Pieza')+'</b><br>'+String(detail.ownerSpaceId?'Pertenece al espacio '+detail.ownerSpaceId:'Pieza general del módulo');
    id('material_piece_group').value=group;id('material_piece_custom').value=current.color||current.texture?'SI':'NO';id('material_piece_color').value=current.color||detail.materialColor||groupColor(group);id('material_piece_name').value=current.name||detail.materialName||'';id('material_piece_edge').value=current.edge||'INHERIT';id('material_piece_edge_color').value=current.edgeColor&&current.edgeColor!=='INHERIT'?'CUSTOM':'INHERIT';id('material_piece_edge_custom_color').value=current.edgeColor&&current.edgeColor!=='INHERIT'?current.edgeColor:(current.color||detail.materialColor||groupColor(group));pendingPieceTexture=current.texture||'';id('material_piece_texture_url').value=pendingPieceTexture&&!pendingPieceTexture.startsWith('data:')&&!pendingPieceTexture.startsWith('INCLUDED:')?pendingPieceTexture:'';if(id('material_piece_texture_included'))id('material_piece_texture_included').value=pendingPieceTexture.indexOf('INCLUDED:')===0?pendingPieceTexture.slice('INCLUDED:'.length):'';id('material_piece_rotation').value=current.rotation==null?'INHERIT':String(current.rotation);previewAt('material_piece_texture_preview',pendingPieceTexture,'Heredar textura');
    var sizing=dimensionOverrides[selectedKey]||{};
    if(id('material_piece_oversize_ancho'))id('material_piece_oversize_ancho').value=sizing.delta_ancho||0;
    if(id('material_piece_oversize_prof'))id('material_piece_oversize_prof').value=sizing.delta_prof||0;
    if(id('material_piece_oversize_alto'))id('material_piece_oversize_alto').value=sizing.delta_alto||0;
    var miter=miterOverrides[selectedKey]||{};
    if(id('material_piece_miter_corner'))id('material_piece_miter_corner').value=miter.corner||'';
    if(id('material_piece_miter_size'))id('material_piece_miter_size').value=miter.size||20;
    renderList();
  }
  function renderList(){
    var host=id('material_piece_list');if(!host)return;var term=String(value('material_piece_search','')).toLowerCase(),list=pieces();host.innerHTML='';
    list.filter(function(piece){return !term||piece.name.toLowerCase().indexOf(term)>=0;}).forEach(function(piece){var key=piece.materialKey||piece.pieceId,button=document.createElement('button');button.type='button';button.className='material-piece-button'+(key===selectedKey?' active':'');button.innerHTML='<span>'+piece.name+'</span><i class="material-chip" style="background:'+resolved(piece)+'"></i>';button.onclick=function(){if(window.Modular3DView)window.Modular3DView.selectPieceByKey(key);selectDetail({pieceId:piece.pieceId,materialKey:key,materialGroup:piece.group,materialName:piece.materialName,materialColor:piece.color,name:piece.name,ownerSpaceId:piece.ownerSpaceId});};host.appendChild(button);});
    var customCount=Object.keys(overrides).length,doors=list.filter(function(p){return p.category==='front';}).length,summary=id('material_summary');if(summary)summary.innerHTML='<span>'+list.length+' piezas</span><span>'+customCount+' personalizadas</span><span>'+doors+' frentes</span><span>'+(list.length?'Vista sincronizada':'Calculando...')+'</span>';
  }
  function refresh(){
    if(window.actualizarVista)window.actualizarVista();
    setTimeout(function(){renderList();if(selectedKey&&window.Modular3DView)window.Modular3DView.selectPieceByKey(selectedKey);renderSummary();},30);
  }
  function renderSummary(){
    var host=id('material_build_summary'),validation=id('material_validation');if(!host)return;var list=pieces(),groupCounts={};list.forEach(function(p){var g=(overrides[p.materialKey]||{}).group||p.group;groupCounts[g]=(groupCounts[g]||0)+1;});
    host.innerHTML='<p><strong>Asignación:</strong> '+groups.map(function(g){return g+' '+(groupCounts[g]||0);}).join(' · ')+'</p><p><strong>Personalizadas:</strong> '+Object.keys(overrides).length+' pieza(s). Selecciona una pieza en azul para comprobar su acabado.</p>';
    if(validation){validation.textContent=list.length?'Materiales listos para construir. Los acabados individuales tienen prioridad sobre su grupo.':'Aún no hay piezas calculadas.';validation.className='message warn show';}
  }
  function applySelected(){
    if(!selectedKey||!selectedDetail){id('material_piece_info').textContent='Selecciona primero una pieza.';return;}
    var custom=id('material_piece_custom').value==='SI',group=id('material_piece_group').value,edge=id('material_piece_edge').value,edgeColor=id('material_piece_edge_color').value==='CUSTOM'?id('material_piece_edge_custom_color').value:'INHERIT',rotation=id('material_piece_rotation').value;
    if(custom||edge!=='INHERIT'||edgeColor!=='INHERIT'||pendingPieceTexture||rotation!=='INHERIT')overrides[selectedKey]={group:group,color:custom?id('material_piece_color').value:'',name:custom?(id('material_piece_name').value||'Material personalizado'):'',texture:pendingPieceTexture,rotation:rotation,edge:edge,edgeColor:edgeColor};else delete overrides[selectedKey];
    var deltaAncho=Number(value('material_piece_oversize_ancho',0))||0,deltaProf=Number(value('material_piece_oversize_prof',0))||0,deltaAlto=Number(value('material_piece_oversize_alto',0))||0;
    if(deltaAncho||deltaProf||deltaAlto)dimensionOverrides[selectedKey]={delta_ancho:deltaAncho,delta_prof:deltaProf,delta_alto:deltaAlto};else delete dimensionOverrides[selectedKey];
    var miterCorner=value('material_piece_miter_corner',''),miterSize=Number(value('material_piece_miter_size',20))||0;
    if(miterCorner&&miterSize>0)miterOverrides[selectedKey]={corner:miterCorner,size:miterSize};else delete miterOverrides[selectedKey];
    refresh();
  }
    function clearSelected(){if(selectedKey){delete overrides[selectedKey];delete dimensionOverrides[selectedKey];delete miterOverrides[selectedKey];}pendingPieceTexture='';if(id('material_piece_texture_included'))id('material_piece_texture_included').value='';if(id('material_piece_custom'))id('material_piece_custom').value='NO';if(id('material_piece_edge'))id('material_piece_edge').value='INHERIT';if(id('material_piece_edge_color'))id('material_piece_edge_color').value='INHERIT';if(id('material_piece_texture_url'))id('material_piece_texture_url').value='';if(id('material_piece_rotation'))id('material_piece_rotation').value='0';if(id('material_piece_oversize_ancho'))id('material_piece_oversize_ancho').value=0;if(id('material_piece_oversize_prof'))id('material_piece_oversize_prof').value=0;if(id('material_piece_oversize_alto'))id('material_piece_oversize_alto').value=0;if(id('material_piece_miter_corner'))id('material_piece_miter_corner').value='';if(id('material_piece_miter_size'))id('material_piece_miter_size').value=20;previewAt('material_piece_texture_preview','');refresh();}
  function bind(){
    if(bound)return;bound=true;
    var original=window.datosFormulario;
    window.datosFormulario=function(){var data=original();groups.forEach(function(group){data['material_'+group+'_color']=value('material_'+group+'_color','');data['material_'+group+'_nombre']=value('material_'+group+'_nombre','');data['material_'+group+'_custom']=checked('material_'+group+'_custom')?'SI':'NO';});data.material_unico=checked('material_unico')?'SI':'NO';data.material_global_color=value('material_global_color','#ffffff');data.material_global_nombre=value('material_global_nombre','Blanco');data.edge_mode=value('edge_mode','MIXED');data.edge_inherit_color=checked('edge_inherit_color')?'SI':'NO';data.material_overrides_json=JSON.stringify(overrides);data.material_textures_json=JSON.stringify(textures);data.material_texture_meta_json=JSON.stringify(textureMeta);data.dimension_overrides_json=JSON.stringify(dimensionOverrides);data.miter_overrides_json=JSON.stringify(miterOverrides);return data;};
    groups.forEach(function(group){['color','nombre'].forEach(function(field){var node=id('material_'+group+'_'+field);if(node)node.addEventListener('input',function(){if(checked('material_unico'))id('material_'+group+'_custom').checked=true;refresh();});});var custom=id('material_'+group+'_custom');if(custom)custom.addEventListener('change',refresh);});
    id('material_piece_search').addEventListener('input',renderList);id('material_piece_apply').addEventListener('click',applySelected);id('material_piece_clear').addEventListener('click',clearSelected);
    function syncGlobal(fromMaterials){var enabled=fromMaterials?checked('material_unico_materiales'):checked('material_unico'),color=value(fromMaterials?'material_global_color_materiales':'material_global_color','#ffffff'),name=value(fromMaterials?'material_global_nombre_materiales':'material_global_nombre','Blanco');id('material_unico').checked=enabled;id('material_unico_materiales').checked=enabled;id('material_global_color').value=color;id('material_global_color_materiales').value=color;id('material_global_nombre').value=name;id('material_global_nombre_materiales').value=name;refresh();}
    ['material_unico','material_global_color','material_global_nombre'].forEach(function(key){id(key).addEventListener(key==='material_unico'?'change':'input',function(){syncGlobal(false);});});
    ['material_unico_materiales','material_global_color_materiales','material_global_nombre_materiales'].forEach(function(key){id(key).addEventListener(key==='material_unico_materiales'?'change':'input',function(){syncGlobal(true);});});
    id('material_apply_all').addEventListener('click',function(){id('material_unico_materiales').checked=true;syncGlobal(true);});
    id('material_restore_groups').addEventListener('click',function(){id('material_unico_materiales').checked=false;syncGlobal(true);});
    id('material_clear_overrides').addEventListener('click',function(){if(confirm('¿Eliminar todas las excepciones individuales de material?')){overrides={};refresh();}});
    function syncGlobalPreview(){var source=textures.global||'';previewAt('material_global_preview',source,'Color sólido');previewAt('material_global_preview_materiales',source,'Color sólido');}
    if(id('material_texture_included'))fillIncludedSelect(id('material_texture_included'));
    id('material_texture_group').addEventListener('change',function(){pendingTexture=textures[this.value]||'';var meta=textureMeta[this.value]||{};id('material_texture_url').value=(pendingTexture.indexOf('data:')===0||pendingTexture.indexOf('INCLUDED:')===0)?'':pendingTexture;if(id('material_texture_included'))id('material_texture_included').value=pendingTexture.indexOf('INCLUDED:')===0?pendingTexture.slice('INCLUDED:'.length):'';id('material_texture_scale').value=meta.scale||600;id('material_texture_rotation').value=String(meta.rotation||0);previewTexture(pendingTexture);});
    id('material_texture_url').addEventListener('input',function(){pendingTexture=this.value.trim();if(id('material_texture_included'))id('material_texture_included').value='';previewTexture(pendingTexture);});
    id('material_texture_file').addEventListener('change',function(){imageFileToData(this.files&&this.files[0],function(data){pendingTexture=data;if(id('material_texture_included'))id('material_texture_included').value='';previewTexture(data);},function(message){alert(message);});});
    if(id('material_texture_included'))id('material_texture_included').addEventListener('change',function(){if(!this.value)return;var tex=includedTexture(this.value);if(!tex)return;pendingTexture='INCLUDED:'+tex.id;id('material_texture_url').value='';id('material_texture_scale').value=tex.defaultScale;previewTexture(pendingTexture);});
    id('material_texture_apply').addEventListener('click',function(){var group=value('material_texture_group','casco');if(pendingTexture)textures[group]=pendingTexture;textureMeta[group]={scale:Number(value('material_texture_scale',600))||600,rotation:Number(value('material_texture_rotation',0))||0};if(group==='global')syncGlobalPreview();refresh();});
    id('material_texture_clear').addEventListener('click',function(){var group=value('material_texture_group','casco');delete textures[group];pendingTexture='';id('material_texture_url').value='';previewTexture('');if(group==='global')syncGlobalPreview();refresh();});
    id('material_library_save').addEventListener('click',function(){var group=value('material_texture_group','global'),name=group==='global'?value('material_global_nombre','Material'):value('material_'+group+'_nombre','Material'),color=group==='global'?value('material_global_color','#ffffff'):groupColor(group),items=library();name=name.trim()||'Material';items.push({name:name,color:color,texture:textures[group]||pendingTexture||'',scale:Number(value('material_texture_scale',600))||600,rotation:Number(value('material_texture_rotation',0))||0});saveLibrary(items);});
    id('material_library_use').addEventListener('click',function(){var index=parseInt(value('material_library_select',''),10),item=library()[index];if(!item)return;var group=value('material_texture_group','global');if(group==='global'){id('material_global_nombre').value=item.name;id('material_global_nombre_materiales').value=item.name;id('material_global_color').value=item.color;id('material_global_color_materiales').value=item.color;}else{id('material_'+group+'_nombre').value=item.name;id('material_'+group+'_color').value=item.color;}textures[group]=item.texture||'';textureMeta[group]={scale:item.scale||600,rotation:item.rotation||0};pendingTexture=textures[group];id('material_texture_scale').value=textureMeta[group].scale;id('material_texture_rotation').value=String(textureMeta[group].rotation);previewTexture(pendingTexture);syncGlobalPreview();refresh();});
    id('material_global_file').addEventListener('change',function(){imageFileToData(this.files&&this.files[0],function(data){textures.global=data;id('material_global_source').value='FILE';syncGlobalPreview();refresh();},function(message){alert(message);});});
    id('material_global_url').addEventListener('change',function(){var source=this.value.trim();if(source){textures.global=source;id('material_global_source').value='URL';syncGlobalPreview();refresh();}});
    id('material_global_source').addEventListener('change',function(){if(this.value==='COLOR'){delete textures.global;syncGlobalPreview();refresh();}else if(this.value==='FILE'){id('material_global_file').click();}else if(this.value==='URL'){id('material_global_url').focus();}else if(this.value==='LIBRARY'){id('material_texture_group').value='global';id('material_library').scrollIntoView({behavior:'smooth',block:'center'});}else if(this.value==='INCLUDED'){id('material_texture_group').value='global';if(id('material_texture_included'))id('material_texture_included').scrollIntoView({behavior:'smooth',block:'center'});}});
    id('material_global_scale').addEventListener('input',function(){textureMeta.global=textureMeta.global||{};textureMeta.global.scale=Number(this.value)||600;refresh();});id('material_global_rotation').addEventListener('change',function(){textureMeta.global=textureMeta.global||{};textureMeta.global.rotation=Number(this.value)||0;refresh();});
    id('material_global_choose_file').addEventListener('click',function(){id('material_global_file').click();});id('material_global_use_url').addEventListener('click',function(){var source=id('material_global_url').value.trim();if(!source){source=prompt('Pega el enlace directo JPG, PNG o WebP:','')||'';id('material_global_url').value=source;}if(source){textures.global=source;id('material_global_source').value='URL';syncGlobalPreview();refresh();}});id('material_global_clear_texture').addEventListener('click',function(){delete textures.global;id('material_global_source').value='COLOR';syncGlobalPreview();refresh();});
    id('material_piece_texture_url').addEventListener('change',function(){pendingPieceTexture=this.value.trim();if(id('material_piece_texture_included'))id('material_piece_texture_included').value='';previewAt('material_piece_texture_preview',pendingPieceTexture,'Heredar textura');});id('material_piece_texture_file').addEventListener('change',function(){imageFileToData(this.files&&this.files[0],function(data){pendingPieceTexture=data;if(id('material_piece_texture_included'))id('material_piece_texture_included').value='';previewAt('material_piece_texture_preview',data,'Heredar textura');},function(message){alert(message);});});
    if(id('material_piece_texture_included')){fillIncludedSelect(id('material_piece_texture_included'));id('material_piece_texture_included').addEventListener('change',function(){if(!this.value)return;var tex=includedTexture(this.value);if(!tex)return;pendingPieceTexture='INCLUDED:'+tex.id;id('material_piece_texture_url').value='';previewAt('material_piece_texture_preview',pendingPieceTexture,'Heredar textura');});}
    id('material_library_delete').addEventListener('click',function(){var index=parseInt(value('material_library_select',''),10),items=library();if(!items[index])return;items.splice(index,1);saveLibrary(items);});
    window.addEventListener('modular3d:pieceSelected',function(event){selectDetail(event.detail||{});});
    window.addEventListener('modular3d:pageShown',function(event){if(event.detail&&event.detail.id==='diseno')setTimeout(function(){renderList();renderSummary();},30);});
    var oldLoad=window.Modular3DLoadInitial;window.Modular3DLoadInitial=function(data){oldLoad(data);groups.forEach(function(group){['color','nombre'].forEach(function(field){var node=id('material_'+group+'_'+field),key='material_'+group+'_'+field;if(node&&data[key])node.value=data[key];});});id('material_unico').checked=data.material_unico==='SI';id('material_global_color').value=data.material_global_color||'#ffffff';id('material_global_nombre').value=data.material_global_nombre||'Blanco';id('material_unico_materiales').checked=id('material_unico').checked;id('material_global_color_materiales').value=id('material_global_color').value;id('material_global_nombre_materiales').value=id('material_global_nombre').value;try{overrides=typeof data.material_overrides_json==='string'?JSON.parse(data.material_overrides_json):data.material_overrides_json||{};}catch(_e){overrides={};}try{dimensionOverrides=typeof data.dimension_overrides_json==='string'?JSON.parse(data.dimension_overrides_json):data.dimension_overrides_json||{};}catch(_d){dimensionOverrides={};}try{miterOverrides=typeof data.miter_overrides_json==='string'?JSON.parse(data.miter_overrides_json):data.miter_overrides_json||{};}catch(_mo){miterOverrides={};}try{textures=typeof data.material_textures_json==='string'?JSON.parse(data.material_textures_json):data.material_textures_json||{};}catch(_t){textures={};}try{textureMeta=typeof data.material_texture_meta_json==='string'?JSON.parse(data.material_texture_meta_json):data.material_texture_meta_json||{};}catch(_m){textureMeta={};}pendingTexture=textures[value('material_texture_group','casco')]||'';id('material_global_source').value=!textures.global?'COLOR':(String(textures.global).indexOf('https://')===0?'URL':(String(textures.global).indexOf('INCLUDED:')===0?'INCLUDED':'FILE'));id('material_global_url').value=id('material_global_source').value==='URL'?textures.global:'';if(id('material_texture_included'))id('material_texture_included').value=pendingTexture.indexOf('INCLUDED:')===0?pendingTexture.slice('INCLUDED:'.length):'';id('material_global_scale').value=(textureMeta.global&&textureMeta.global.scale)||600;id('material_global_rotation').value=String((textureMeta.global&&textureMeta.global.rotation)||0);syncGlobalPreview();previewTexture(pendingTexture);refresh();};
    var materialLoadWithGroups=window.Modular3DLoadInitial;
    window.Modular3DLoadInitial=function(data){materialLoadWithGroups(data);groups.forEach(function(group){var custom=id('material_'+group+'_custom');if(custom)custom.checked=data['material_'+group+'_custom']==='SI';});refresh();};
    if(window.__modular3dInitial)window.Modular3DLoadInitial(window.__modular3dInitial);
    setTimeout(function(){renderList();renderSummary();renderLibrary();},80);
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(bind,0);});else setTimeout(bind,0);
}());
